### ISSUE TITLE
What new tool/tech are you most excited about right now?

### ISSUE THREAD

**Issue by mattfairley** [wesbos/ama#10]
What are you really pumped to learn that you think has really great potential or would just be fun.

**Comment by wesbos** [comment]
Right now I think Gulp is that tech - and it's not just because I run a course and I'm writing a book. I teach and write about things that I both find exciting and can bring maximum bang to a developer's workflow. 

If you put in a solid 5-10 hours with Gulp over a month or so, you can get really good at it. It's super easy to learn, the community is extremely vibrant and it just so simple for what it can do for you.

Because of gulp we are starting to see much more advanced workflows in beginner and intermediate developers, which leads to smaller, better and faster websites.

**Comment by ssteinerx** [comment]
Ready to review whenever you're ready @wesbos.
