### ISSUE TITLE
Three Great Questions!

### ISSUE THREAD

**Issue by emmyyusufu** [wesbos/ama#100]
Hello, I'm an undergrad nd have been learning Web Development for about 1 year+ now (MEAN dev. specifically) through online specializations and in-person courses. I am looking to put my knowledge/skills into use especially by starting a Web Dev. business and Instructing an in-person course.

My questions are: 
1. Should I and how do I go about creating a profitable web development business after university?
2. I see some advise online to drop programming skills and depend on wordpress for a web dev. business. What do you think about this?
3. How do I actually get an idea for creative/innovative applications with my web dev skills, as opposed to small things built in online tutorials and courses?

**Comment by wesbos** [comment]
1. Should I and how do I go about creating a profitable web development business after university?

It's really just two things: First, people need to know what you do, so make sure you tell people that you offer web development series. Second, you need to be reputable. It's hard to find people you can trust, so that goes a long way.
1. I see some advise online to drop programming skills and depend on wordpress for a web dev. business. What do you think about this? 

Wordpress still needs lots of programming skills. You can make some good money on WordPress, but make sure that your skillset can change platforms when your interests or the market change. 
1. How do I actually get an idea for creative/innovative applications with my web dev skills, as opposed to small things built in online tutorials and courses?

Just keep building small things and you will start to come up with bigger and bigger ideas - it starts to flow once you get good at programming :)
