### ISSUE TITLE
What is the best resource for learning modern JavaScript from scratch? 

### ISSUE THREAD

**Issue by hardikdangar** [wesbos/ama#101]

**Comment by wesbos** [comment]
Funny enough, I actually don't know. 

I get this question all the time and because it's been so long since I've learned it, I always ask others. It becomes some sort of mix of codecademy, Jon duckett's book and some other online resources.

In 2017 I'll be working on a JS from scratch series that I hope will be the de facto _how to learn modern JavaScript_ course. There is a lot to learning JavaScript so I've been taking notes and planning it for a while and I think I'm getting close to creating something.

**Comment by deanhtid** [comment]
Also spoke to you on Twitter about this, but can't wait and hopefully we can dig in and get learning soon :)

**Comment by krl87** [comment]
Awesome! I really hope to see this course too. Didn't feel any of the JS classing in my program at Georgian benefited me whatsoever.
