### ISSUE TITLE
How do you design your courses?

### ISSUE THREAD

**Issue by carinakoo** [wesbos/ama#106]
Is there a method to the choice of content? The structure?

**Comment by wesbos** [comment]
Good question! 

For the content, I have a file called `ideas.md` in which I keep all my ideas for future courses. When the ideas start flowing I just jot down what a video series could possibly include as well as what we will make. 

Once I get a good enough feeling that people are looking for a really good series on a topic (React, ES6, Flexbox...) then I'll commit to building it out. 

Now in terms of structure, I go two different ways:

My [React](https://ReactforBeginners.com) and [Redux](https://LearnRedux.com) series build upon projects, we learn all the different pieces of React as we build an app. This makes a lot of sense when learning react because you can learn a concept and immediately put it into place. 

Before I start any videos or structure, I always create what we will be building in the video. It has to be fun, it has to look good and it has to cover all the concepts I wish to get across in the video. 

My [ES6](https://ES6.io) series, along with a few others are more piecemeal in which we learn individual concepts and build smaller things along the way. This is nice for when you need to reference a specific concept or perhaps skip over an entire section that you are already comfortable. While the concepts do build upon each other, it's much less of a linear learning journey. 

So, really the structure is "How do I best explain these concepts?" and use that. I never pay attention to length or any other metric - it's just ensuring the the learners who buy my courses get the best experience for whatever topic they chose to learn.
