### ISSUE TITLE
What is your salary in USD?

### ISSUE THREAD

**Issue by f00Dev** [wesbos/ama#114]
Hey Wes,

What do you make in the industry for annual compensation, and do you feel that your salary commensurate's with your experience?

If not a number, than a range, perhaps from when you started to present?

Thanks!

**Comment by wesbos** [comment]
I don't make a salary because I work for myself so it's a bit more complicated. But if I'm generalizing... 

My first year full-time consulting I think I made around 60k and I slowly built that up to about ~150k/year in consulting revenues over about 5 years.  Most of my clients were in the US and I live in Canada - the US dollar has been very strong which makes it very nice for me. This might seem high-ish to some (and low to others), but I need to pay for my own corporate and personal government deductions, health care costs as well as we didn't get a dime for my wife taking off 2+ years of maternity leave. 

I'm not really in tune with industry salaries since I've never had a job, but I've always seen it that I can make more money and have more freedom working for myself. 

Now I've given up that cushy consulting money and I'm trying to make it work selling my own training series :)

**Comment by f00Dev** [comment]
Ah, thank you for sharing. I am trying to see what it would take to make it out on my own, but I have no place to start. I have a corporate job making good money with good benefits, and its hard to think about giving that up to start on my own, especially with little ones :)

**Comment by wesbos** [comment]
Yeah it is tough - you would have to start moonlighting for a few months until you can build up your client base
