### ISSUE TITLE
Are you worried about a creating a Wes Bos Clone Army of developers, all using Oh-My-ZSH and Sublime Text with identical configurations?

### ISSUE THREAD

**Issue by growdigital** [wesbos/ama#117]

**Comment by wesbos** [comment]
hahaha - I think it's cool that a lot of people like my setup.

Themes and prompts are very much a personal preference so I never tell people to use them, or that it's the 'best way'. 

I intentionally do not share a list of my ESlint preferences or Sublime packages because I don't want people just to copy them 1:1, but figure out why they should be using something.
