### ISSUE TITLE
How did you get your first dozen or so consulting gigs?

### ISSUE THREAD

**Issue by agm1984** [wesbos/ama#119]
I am stalking you btw. Your interests are extremely similar to my own, except I have more mobile app dev cycle, SQA and marketing angle (and modding cars and bodybuilding). We may have talked about this briefly on Twitter PM.

I'm trying to establish into a consulting role, and I'm incredibly curious to hear about your early footsteps and what panned out and what you think a person should certainly do.

My opener question would be, well a) is this GitHub activity here dofollow in terms of SEO juice aka nectar, or did you have zero intentions there when you were making this AMA? I really love the idea TBH. I love the idea of submitting issues with tracking. It makes my QA senses tingle, and my customer service and feedback management senses are off the hook also.

Critical question b) what methods and properties were most fruitful for you gaining traction with consulting? I would prefer if you could be verbose :)

Thanks,
Adam

**Comment by wesbos** [comment]
Good question! 

a) Not at all - it was just a way for me to keep questions out in the open - I don't like answering these types of questions over email because they only benefit the asker - this way hundreds of people can read the answers and hopefully get something from it!

b) 

Back in the day, it was alllll about tweet-ups. There were like 200 people in Toronto on twitter so it was super easy to meet people. I was lucky enough to meet Satish and Verne who ran Jet Cooper (since acquired and turned into Shopify Toronto). From there my name was passed around the community and I soon had lots of work. 

Obviously tweet ups aren't the best way anymore, but the key here was meeting as many people as I could and letting them know I was looking for work. So many consultants think that the work will magically come to them, or if they have a github project people will find them. Those things work, but you have to straight up ask as many people as you need for work. 

Once you gain a reputation as a **reliable** consultant, it will all start to flow it. It's really hard to find people who are good, reliable and in it for the long term (not just temporarily unemployed, but running a business).

Also I taught workshops at Ladies Learning Code which positioned me to _look_ like an expert.  Look being the keyword there ;)  Lots of work came from that. 

So - just get out there, be super visible and tell everyone what you do.

**Comment by agm1984** [comment]
I understand the metrics behind your logic :)

Thanks for the reply. In my opinion, it is all about two things:
1) how many new people are you meeting?
2) how many new keywords are you learning?

This means you must be an open network, not a closed network -- open to connections with new keywords and new people 24/7.

I will report back at some point.

**Comment by wesbos** [comment]
👍 Good luck
