### ISSUE TITLE
What do you think of this ?

### ISSUE THREAD

**Issue by gj1118** [wesbos/ama#12]
http://mashable.com/2015/07/06/why-web-design-dead/?utm_cid=mash-prod-email-velocity-alert&utm_source=newsletter&utm_medium=email&utm_campaign=velocity&utm_emailalert=viral

**Comment by kleinfreund** [comment]
utm_cid, utm_source, utm_media, utm_campaign, utm_emailalert. 

Did not click.

**Comment by gj1118** [comment]
Here is the abridged version of that link http://mashable.com/2015/07/06/why-web-design-dead .... you can also view this article on mashable

**Comment by wesbos** [comment]
The UTMs are just just because it's a link from from an email or similar - no biggie :) 

Vitaly posted a great response to this this morning → http://www.smashingmagazine.com/2015/07/08/web-design-is-dead-no-it-isnt/

To say templates are going to replace custom websites is a joke, there is so much more that goes into a successful business website than a templates. Being able to use your website and turn it into leads and new customers is invaluable and a must have part of running a business today.

Some areas of sites will definitely be replaced. A landscaping company or local spa really might not need a $5,000 custom site - they just need a brochure site - in which case a template, squarespace or something like the grid is a great choice.

Web development will always be changing, and what we do is going to be changing. Just because we have been creating what we think are websites for the last 5 years, doesn't mean thats what we will be making in the next 5.  It's already changing as we see web developers get more specialized into UX, JavaScript apps, Mobile or anything else. 

Like any other industry, we just need to adapt with the space. Ours just moves a little faster.

**Comment by gj1118** [comment]
Thank You @wesbos for taking time out to answer that one.. When I saw that one, I was worried as hell for sure.. :+1:
