### ISSUE TITLE
How / why do you reply to most if not all tweets that come your way?

### ISSUE THREAD

**Issue by dan-gamble** [wesbos/ama#128]
From what i can remember every tweet i've sent you're way at the very least i've had some kind of "like" or "favourite" if not a reply.

You're a dude that has a huge following and you always seem ready to reply to anyone about anything you tweet. How on earth do you keep track of it all and more-so why do you do it?

I know a lot of people who have far less followers than yourself who tweet things but very rarely interact with anyone who interacts with them.

**Comment by wesbos** [comment]
Ohh good question!

**Why** do I do it? Twitter is all about community - too many people are "pushers" who just push content out there and expect it to pay huge dividends. I didn't get 80k followers just tweeting links out, I did it by being part of the conversation everyday for 10 years.

Spending 30 seconds to answer a question often means someone will buy a $70 course at some point in their life, or recommend my free stuff to a friend. The math works out! 

Plus I also learn a lot by talking to people on twitter - there are some really smart people replying to me so I like to take advantage of that because I don't have any co-workers or mentors who are experts in areas I'd like to grow. 

**How?** I'm a huge Tweetdeck power user. I've got 16 columns right now, each with finely tuned filters. I know the keyboard shortcuts cold and I've got a ton of text expander snippets and workflows that I use to take care of common things like replying what font, text editor, theme or auto-completion package I use.

I've been using hearts as a way of both letting myself know I've read the tweet, and also a head-nod of appreciation to the person tweeting at me. I don't always get everything, especially on weekends. 

I'd love to build some sort of app that makes twitter mentions like an inbox, letting me archive things once I've dealt with it. 

So yeah - I've been on twitter for almost 10 years now and I owe much of my career to being in conversations to it :)

**Comment by dan-gamble** [comment]
Awesome answer. I fully get your point about building relationships. I bought your React & Sublime courses, i don't actually use either, just to support you because of all the things you offer free and paid and that you're so approachable. Thanks man, keep it up 👍

**Comment by wesbos** [comment]
Oh wow - thanks so much :) seriously, your support means I can keep cranking out more content :)
