### ISSUE TITLE
If you were to do one thing to jump start a current career, what would it be?

### ISSUE THREAD

**Issue by benpetersen** [wesbos/ama#14]

**Comment by wesbos** [comment]
Make stuff, blog about it, share it with everyone. Don't worry if it's not good enough - the web development industry is incredibly supportive of you trying things out!

Seriously, every good thing that has ever happened to my careers is because I made something and blogged about it. Still to this day I'm amazed at the power that blogging has. It's as if you post a blog post about something, you are immediately an expert. 

Just a few examples:

* Flown to California to speak at a conference about this. Lots of paid gigs implementing in private apps →  http://wesbos.com/html5-video-face-detection-canvas-javascript/ 
* I did a few smaller WordPress posts years ago which led me to teaching at [Ladies Learning Code](http://ladieslearningcode.com/) which led to tons of paid WordPress work and my current teaching position at [Hackeryou](http://hackeryou.com)
* Invited to speak at a conference in India about this → http://wesbos.com/overwhelmed-with-web-development/
* 10k worth of paid work implementing this into a dentist's iPad and web app → http://wesbos.com/html5-canvas-websockets-nodejs/
* My sublime text blog posts led to an audience which I could write a book for
* Tons of job offers and lots of paid work → http://wesbos.com/interviewing-with-google/

I don't have a large blog - I get less than 2,000 hits per day and I only have a few handfuls of posts. It's not the size of the audience that really matters. Enough people will find you and pay you to do work you love. 

Doors open when you share what you know!

**Comment by nickedes** [comment]
:+1:

**Comment by cdmedia** [comment]
+1 to this. Thanks Wes!

**Comment by MaxAst** [comment]
love that answer, thank you Wes!
