### ISSUE TITLE
<script> in <head> or <body>

### ISSUE THREAD

**Issue by mattlg24** [wesbos/ama#144]
Hey Wes,

I'm going through your JavaScript 30 course (it's awesome so far), but I'm having issues on the JavaScript Drum Kit. When I link my app.js in my head tag (like this - <script type="text/javascript" src="app.js"></script>) my removeTransition doesn't work. And when I put the <script> at the bottom of the body tag in my index.html it does work. Why?

Matt

**Comment by wesbos** [comment]
Hey! This is because the JavaScript in the head tag executes immediately - and that is before any of the elements on the page exist. 

But putting it after the elements are on the page, you ensure they exist before you run the code to use them.

As a _general_ rule of thumb it's best to put all your JS after your content. If you do need something in the head you can use something called DOMContentLoaded which is similar to jQuery documentr.eady()

**Comment by konekoya** [comment]
Found one typo here: it should be `document.ready()`, not `documentr.eady()`

**Comment by wesbos** [comment]
I much prefer `documentr.eady()` for it's performance advantages
