### ISSUE TITLE
Your Ramen Recipe

### ISSUE THREAD

**Issue by danrichman** [wesbos/ama#145]
Hi Wes,

I noticed [on Twitter](https://twitter.com/wesbos/status/706608787046662145), you're a fan of making homemade ramen. What's your recipe?

**Comment by wesbos** [comment]
![](https://pbs.twimg.com/media/Cc5g8qdWEAE0sQ8.jpg)

Mmm I love ramen. I've only made it a few times so I'm still learning, but this is roughly my best recipe yet. I don't really measure things so I'd look up some recipes if you need amounts. 

**broth** 

1. Start with a bunch of beef broth. Generally about 1 box of broth.
2. Add in a bunch of Tamari (organic soy sauce, low sodium). Sometimes I'll add water as I taste if it's too salty. Generally about a cup.
3. Ginger / Sea Salt / sesame oil / garlic / other.
4. I like to add some thinly sliced carrots
5. The best time I've done it, I smoked some pork but "steaks" and then put them in the broth. It was amazing because the ramen had a smokey flavour.  Any fatty cut of a pork will work out - you can put it in raw too. 

**Eggs** - I've spent a lot of time figuring out how to get the perfect ramen egg. Most of them call for room temp eggs, which is BS because who has time to wait for that? 

1. Boil water
2. Take eggs from fridge, slowly submerge them into the boiling water
3. wait 8 mins
4. Drain the boiling water, fill with cold cold cold water and as much ice as you have

**Toppin's**
Once you have the crock pot going for 4+ hours (the longer the better), you can serve it. 

For noodles, I found I like the instant ramen noodles from the asian grocery store best. Throw away the flavour pack.  Cover noodles with broth.

Top with green onion, mushrooms and whatever else you like. I've been trying radicchio (it's like a small cabbage) and I like the bitterness of it. 

Throw in one of your boiled eggs and instagram that puppy!
