### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by proudfeet** [wesbos/ama#15]
What 2-3 changes that you have made in the last 12 months were you most resistant to, and why? What were the outcomes of these changes and what effect (positively or negative) did they have?

**Comment by wesbos** [comment]
Oof - great question. This one will take some thinking. 

These are all pretty small changes, but have helped my work quite a bit:

1. New chair. I've been holding off buying a new desk chair for a long time. I finally dropped $1200 on a new Aeron, and its been unreal. I can focus on tasks for longer because the chair is super comfortable.  

2. Client Work. I love client work - I really do. It pays for a big portion of my income. I've got lots of cool projects come my way, and I can only say yes to a few of them. If I get myself into too much client work, it affects my other projects, which I ultimately want to be doing anyways.  So, deciding to say "No" more often (but not all the time, I still need to do lots of client work to keep my skills up) has been really hard, because I love to work with people, but it's been great. 


3. Sleep. I get and need tons of it. At least 7-9 hours a night. I've found going to bed earlier has helped me get up earlier, and thus allowed me to enjoy my mornings more. When I'm not racing to get into my office, I can spend time with my Family and it really sets the tone for a kickass workday.
