### ISSUE TITLE
Do you use any wireframing tools when designing the websites for your course?

### ISSUE THREAD

**Issue by evkwan** [wesbos/ama#150]
Hi Wes, thank you for sharing your knowledge to the world via your courses. The websites for each of your course are really nice and on-point. Do you use any wireframe or mockup tools in particular when creating them? Any that you would recommend for newbie in web designing/developing to use?

Thanks!

**Comment by wesbos** [comment]
Hey! THanks for the question. I find wire framing to be super valuable because it gets the layout out of the way so I can focus on the design. 

I've tried lots of tools for this but since it's just me, and the sites aren't all that complex, I tend to just use a pen and a moleskine notebook. Mine are extremely messy and quickly sketched but its enough for me to put a layout together and then get into Sketch to start designing. 

thanks again!
