### ISSUE TITLE
Do you have any BBQ advice?

### ISSUE THREAD

**Issue by Gpx** [wesbos/ama#156]
I recently bought a new BBQ and I'm looking for tips and recipes. Do you have any advice?

Thanks 🙇

**Comment by wesbos** [comment]
Ohh - what kind?

Off the top of my head:

* Get a thermometer so you know when your meat is done and you don't over/under cook it
* a few splashes of fish sauce on chicken thighs before grilling is the best
* BBQ sauce your meat once it's almost done grilling and keep the lid open - this helps thicken the sauce. If you close the lid, the sauce doesn't thicken up because of the moisture in the air (maybe that is how it works?)  
* If you are doing ribs, boil the shit out of them in salty water first - they will be gross and grey but then you can finish them on the BBQ and they will be amazingly tender

**Comment by Gpx** [comment]
Thank you!

* I have on of these thermometers ![thermometer](https://images-na.ssl-images-amazon.com/images/I/71GoFRKPPRL._SX522_.jpg) I was thinking to buy something with a cable though because my grill has a cover. I heard many people saying that you should not make holes in the meat because the juice will drop out. Do you have any experience with that?
* I never heard of fish sauce on chicken, I'm definitely going to try it!
* Do you add BBQ sauce also before grilling? I saw some recipes where you put it 12 hours before grilling.
* I'm going to try this one too!

**Comment by wesbos** [comment]
An instant read thermometer is great for that. I use one of those for grilling and I've got a wireless one that I use for smoking. 

![](https://pbs.twimg.com/media/Cfiqi-BW4AArHcR.jpg:large)

I don't add bbq sauce before cooking because the sugar will cause it to burn. 

I will marinate though - tons of good recipes for this - one of my favs is soy sauce, ginger, garlic and fish sauce. It makes sort of a Vietnamese chicken that is a umami bomb 👌 

MMM I want to bbq right now
