### ISSUE TITLE
Node starter files?

### ISSUE THREAD

**Issue by hershalb** [wesbos/ama#157]
Hey Wes! For the Learn Node tutorial, you hand off a huge chunk of starter code, how do you go about setting up this environment before you start? Do you have a starter repo that you use for node projects? I wanted to start a project from scratch, but am unsure about where to begin.

Thanks for any help!

**Comment by luftywiranda13** [comment]
@hershalb while you're waiting for @wesbos to answer,
I think you should try [generator-bunny](https://www.npmjs.com/package/generator-bunny)<br />
😄 

inspired by
https://github.com/sindresorhus/generator-nm
https://github.com/kentcdodds/generator-kcd-oss

**Comment by wesbos** [comment]
Hey - great question!

Express has a starter command that will scaffold out the app.js, the equivalent to start.js, and the necessary folders. Pretty similar to what we start with in the tutorial.

So I start with that and then modify it until it's more my coding style, and more up to date with ES6 practices. 

If I were starting a new project today, I'd probably take my tutorial starter files and work from there!

Starters are tricky because you want enough code to start with to give you a good head start, but not too much that you don't know what is going on.

Hope that helps!
