### ISSUE TITLE
What's your ideal website CMS stack today?

### ISSUE THREAD

**Issue by TedAvery** [wesbos/ama#17]
In my experience, a lot of front-facing websites seem to have some common requirements:
- a CMS so your client can update it themselves
- at least some basic access control, so members can sign in and access restricted content
- the freedom to code a totally custom feature if necessary, because no 2 sites are ever the same

What does your setup for a site like this look like? Would Wordpress still be your platform of choice, and if so, what would you do to make it more like a CMS and less like a blog?

**Comment by wesbos** [comment]
Yes! I still love WordPress. I feel it gets a lot of flack for a number of reasons:

1. It's been around forever and it isn't the new shiny thing that we all love
2. Many hobbyist web devs use it to slap together $500 websites and for whatever reason this makes "real" devs angry
3. It has a history of security holes - mostly due to it's size and poorly written plugins
4. PHP just isn't cool. It's not really that nice at all and I'm not a huge fan of it.

That said, even though I'm one of the more edge-developers you would meet, always using new tech. When it comes to the backend, and having a **content** site (not an app, not a store, not a community) that many people want, WordPress is still the best in my opinion. 

This is not because it's the easiest for me to develop, but because it's the easiest for clients to manage by themselves. Many devs put their own needs before the client and end up cooking up some bizarre static site generator only they know how to manage. 

So, I use WordPress for the backend only. I don't use any theme, frameworks, or any other cruft that will hurt my front end. With that I use:

1. Advanced Custom Fields for creating custom backends
2. Custom Post Type UI for all content types
3. Kraken.io Image optimizer so anything the client uploads get automatically smushed
4. ZenCache Pro - for both page caching but also concatenation of all JavaScripts

Then from there, it's just all my regular frontend stuff. I use Gulp to develop the theme. Sometimes it's jQuery, sometimes it's Angular.

**Comment by TedAvery** [comment]
@wesbos Exactly what I was looking for. Thanks a lot :)

**Comment by adrianocr** [comment]
@wesbos that sounds extremely interesting. Maybe you can write a post on how to do that. I'd love to use wordpress as a backend only.

**Comment by wesbos** [comment]
@adrianocr By that I mean I still use the templating system, but i'm not really tied to these PHP heavy wordpress frameworks or custom themes - it's pretty light on the PHP end and most of the magic happens in the DOM.

**Comment by martinwolf** [comment]
I can fully agree. I use WordPress the same way with the same/similar plugins to have a highly custom backend and write all the good frontend stuff from scratch. :+1:

**Comment by glennreyes** [comment]
@wesbos What is your opinion about WP starters themes such as [Sage](https://roots.io/sage/) by Roots?
