### ISSUE TITLE
What's the best way to stay motivated during a long project like writing a book?

### ISSUE THREAD

**Issue by darrinhenein** [wesbos/ama#18]

**Comment by wesbos** [comment]
I think the issue of motivation for most is not necessarily around wanting to do it - most people want to do their project - but when a project is so big it's overwhelming to even think about what to do next and the easiest solution is just to do nothing at all.

Initially when I started to write the book I would just jump in and start writing about whatever I felt I needed next. I found out really quickly that it makes doing a quick hour or so of writing really daunting because the ramp-up time is really long. If you only have a little bit of time to write, the time-to-in-the-groove (TTITG™) is extremely important, you should be able to jump in whenever you have a snack of time. 

So, now when I write, I'll chunk it out into specific sections - for example how to jump around with your cursor in Sublime Text. Once I've got all these sections I can simply tear one off, do the research, brain dump everything in bullet points and then form that into sentences. 

I know this is nothing new and is a well established approach for software development, but it also works really well for writing. I can see these small, manageable sections get whittled down day by day as I write and that really motivates me to keep going.
