### ISSUE TITLE
Enough code talk - any pictures of your vintage race bikes?

### ISSUE THREAD

**Issue by farrelmr** [wesbos/ama#183]
Hi Wes - another cyclist developer here, would love to see some photos of your vintage race bikes

**Comment by wesbos** [comment]
Oof! I probably had ~40 bikes go through my hands over the years. I wish I had kept more pictures of them because I took really good photos when posting them to craigslist. 

This was my first fixed gear, it was stolen

![](https://wes.io/mmIO/contnt)

![](https://wes.io/mncy/content)

These are some of the ones I'd flip. usually bought them for around $100 and flipped for $300-500

![](https://wes.io/mmXl/content)

![](https://wes.io/mmui/content)

This was a haul where I bought maybe 13 bikes for ~$500 and pieced together maybe $2,500 worth of bikes from it

![](https://wes.io/mmd3/content)

I loved Miele

![](https://wes.io/mnJz/content)

Here is a couple more of my keepers. The Bianchi was my pride and joy

![](https://wes.io/mnGo/content)

![](https://wes.io/mmmP/content)

![](https://wes.io/mmsL/content)

I had a really nice Marinoni that I got for $200, it was stolen :( 

![](https://wes.io/mml7/content)

I think that is all I have! That was fun to look back :)

**Comment by gj1118** [comment]
:) you were always an entrepreneur!! 👍

**Comment by farrelmr** [comment]
love the bikes - some classics there
