### ISSUE TITLE
Blog post process

### ISSUE THREAD

**Issue by proudfeet** [wesbos/ama#20]
You mentioned earlier that you blog quite and bit, and spend quite a bit of time on them. Given that, what is your process like? 

Specifically:
* do you write your posts in the Wordpress editor from start to finish, or start them in another program and then bring them over once they're finished and why? 
* do you allow any other people to edit them? 
  * if you do, what do you look for in a good editor?
* I think a lot of would-be bloggers have trouble overcomming the notion that what they're writing about has either a) already been covered or b) could be covered by someone else more qualified - do you have anything that you tell yourself or keep in mind when you reach these kinds of moments?

**Comment by wesbos** [comment]
I've got a folder on my computer called blogposts, and it's full of markdown files. I do all my writing inside of Sublime Text and I use [Marked 2](http://marked2app.com/) by @ttscoff to view the post as I write and format it. Marked2 is one of the best pieces of software I've ever used - love it!

When im done I'll transfer the post from the markdown file to my WordPress install. Sometimes I'll use [GhostText](https://github.com/Cacodaimon/GhostText-for-SublimeText) for Sublime Text to keep them in Sync. 

I think your last point is really important. Most will forgo blogging because someone already posted about it and this is really dangerous. How many times have you been looking to solve a problem or learn a new tech. Do you hit the first tutorial about it and then use that? No way - you probably read 5-6 blog posts and chances are the one you will write will be better or just resonate with some people much better.

I've learned that just because someone else has written or done something already, that doesn't mean you shouldn't. When I was writing my book, someone else released a Sublime Text Book. I almost canned the entire book, but boy am I glad I didn't.
