### ISSUE TITLE
VS Code or Atom for a newbie web developer.

### ISSUE THREAD

**Issue by tompmw** [wesbos/ama#201]

**Comment by pauljacobson** [comment]
Atom and VS Code are pretty similar for the most part. I used Atom for a long time, and enjoyed using it. I liked how I could add multiple projects to a workspace (VS Code introduced this capability in the last month or so).

I switched to VS Code because Atom was a little resource intensive on my MacBook Air (I only have 4GB of RAM). I find VS Code to be less greedy with my MacBook's resources. In addition, VS Code seems to have a lot of the code smarts I use baked in.

You can probably do what you want to do with either. My advice is to try each out. Configure them for what you want to do and see which one you prefer. Also check out Syntax.fm 012: [Why is everyone switching to VS Code?](https://syntax.fm/show/012/why-is-everyone-switching-to-vs-code)
