### ISSUE TITLE
What you've learned since having a child

### ISSUE THREAD

**Issue by proudfeet** [wesbos/ama#21]
Can you give us a few things that you've learned about yourself since having your first child? Which of these was most surprising to you?

**Comment by wesbos** [comment]
I think since having Lux I've been more focused, and driven for the goals that I want to hit. I've only got so much time to work each day so I'm trying to focus and make the best of that. 

I always see very productive people in our industry and wonder how they do it while having kids, and now I totally understand. There is very little that I do that isn't directly related to  investing in work, my business, or the relationships I have outside of work. 

I also noted in another thread the sleep is super important. I don't watch a lot of TV or dick around on reddit, because sleep soooooo much better!
