### ISSUE TITLE
Attic Office?

### ISSUE THREAD

**Issue by iamshawnrice** [wesbos/ama#212]
Hey Wes.

It looks to me as though your office space was formerly an attic. An attic remarkably similar to the one above my house: 

![my attic](https://lh3.googleusercontent.com/NcCZDEq1IlHbWRbdYZLJK34-ImYQrpCWIt-OCkC2gBt7Kz2W3AN0_Y0iGxI-D18uMUAlJChhROlAISSZoETI8oj_5yauYlvte5GXIBujyL0z1t8jIg1t55Ki9na4u9erMyIk7Fm7aKbGP-AWsGJ1tVso3LiMqDTN8-LBGWsBClj_4s0Xl9V1S0TWGv3AqVxlJiNxhdSPm8oH3q09e2m0RFfSwMsSN7jXJ7WUrJH0DCot9d58p7yFWYZJRpUkH-dG7Vxmk7l0rJJ0YwG3vm13a6zshq19_aV8jPcjI6GScn23hWNX0z_k38H1a3D4iMxIXj3NZHJqgIpfyp7nGQrtwTHMWHPcHKd8AQ8KDN4VByKpYpDNLXUab7SBiOI-2cwj6xrM6hL5jtTJc2edleGjsiC0YtwUB4VjmFllLxz2lLQetOsL4Jz0VECjdjX46YzcYvibCfBfNednbVmozKMGIYevJLdy8F5YP7UsCu3Anloq3apTl5gE0fcGUnHp6KOplk2h78QrdF-2ZCjgCRrhuyeaKv0YgOXNEdMIelRCxi9mJht6_QKEoySqy8-ts44NpYTKXxlIRAt6qCNETBXZy9pkvBtGBbYF3JCmuSKAUL07D1XiD3Y72mclx-NTT-cWxPC385Y1RrmjyMespupBOEs0mqHPZb9igQ=w2080-h1560-no)

Is this the case?

Were you involved in the conversion from attic to office? Do you have any images of the rest of the space and/or the conversion process?

**Comment by wesbos** [comment]
That does look pretty similar!  Almost every house in our neighbourhood has a similar attic it seems those with wider houses tend to convert them because you can get some decent living space with the roof line. 

It was already converted for us when we moved in, so all the electrical  and heating was done for us. 

Here is a picture of the office at a fish eye - https://www.instagram.com/p/kx0eiCQcUZ/?tagged=casabos

and once it's painted: https://www.instagram.com/p/n9bQSuwcZg/?tagged=casabos

We installed a bathroom on the top floor foor - I don't have any finished pics but it's really nice:

https://www.instagram.com/p/z3jdPvQcRV/?tagged=casabos
https://www.instagram.com/p/0lonwvwceX/?tagged=casabos

My wife had a similar sized office in the attic too, which is now a guest bedroom

https://www.instagram.com/p/lBRqsDFr05/?tagged=casabos

Totally worth it, esp if you work from home because it's a whole floor away from the noise of kids :)

**Comment by iamshawnrice** [comment]
Great stuff - thanks Wes!
