### ISSUE TITLE
Best customers

### ISSUE THREAD

**Issue by proudfeet** [wesbos/ama#22]
With regard to client work - what are some of the common traits among what you consider to be your best clients?

**Comment by wesbos** [comment]
Before I answer this - I'll say that I love working with clients. I feel many people who are new to freelancing or working for themselves are in a constant fight or battle with their clients. Seems like each end is out to protect themselves rather than to work together to create something amazing. Unfortunately it's usually not just the client who is causing a tense relationship - it's quite often the freelancer doing a poor job at managing the relationship. 

So, how do I find good clients? I'm constantly working on managing the relationship and making working with people really fun. 

That said, there are still some shit clients out there.  Here are a few good things to look out for: 

* Are technical themselves and are trying to solve interesting business or technical problems
* Embrace open source
* Come to your for your expertise, ask for your opinion and recommendations
* Understand timelines but are also quick to move
* 💰💰💰 Have big budgets  - seriously the more you start to charge, the better the clients get!

**Comment by ericvanjohnson** [comment]
Echo a lot of @wesbos.  

A client who:

* Knows what they need.
* Trust in me and my organization.
* Focused.
* Understands what the word 'estimate' means. 
* Flexible 
* Pays on time.
