### ISSUE TITLE
Do you use any service or tool for taxes?

### ISSUE THREAD

**Issue by alvarotrigo** [wesbos/ama#234]
There are online websites that help keep up to date with bills and taxes so at the end of t tax year you can just click a button and get all you need from it.

It all sounds very beautiful when you do bills yourself and have a few clients a month. But whenever you sell things online, like you do, and you have hundreds or thousands of different customers a month with auto generated bills through Stripe or any other service, then things become more complicated.

Those services usually requieres you to add each customer and to create the bill within their system. So basically there are usually 3 options:

- You do this manually 
- You use their API and lose some valuable time coding the integration with Stripe
- If you are lucky, your tax system might have Zappier integration with Stripe

Do you use any system at all? Or you just keep your auto-generated bills, then sum all the earnings and taxes on your own, and give all info to your tax assistant?

**Comment by wesbos** [comment]
Good question! 

For any client work, one off billing, invoice-before-they-buy, business expenses and podcast sponsorships I use Freshbooks - I've used them for about 10 years now and they also have sponsored a majority of the Syntax podcasts :) 

For my courses, which is where most of my income comes from, I've created my own reporting system. Since I have all the sales data in my database, I can pretty easily run reports that calculates:

* Sales volume
* Local Canadian Taxes owed (there are about 13 different ones here in canada that I keep track of)
* Processing Expenses  - paypal and stripe
* Affiliate expenses - when someone refers a course, I deduct that payout from the sales value
* final revenue numbers

Once a year I kick off a huge CSV to my accountant and he runs all the numbers from that.

Invoice/receipts/bills for customers are also generated by this system and are viewable on their course dashboard

hope that helps!
