### ISSUE TITLE
What are the most essential javascript skills for junior developer?

### ISSUE THREAD

**Issue by ottoo** [wesbos/ama#24]
I was wondering, what do you think are the most inportant skills for a junior front end developer? Which advanced topics?

**Comment by wesbos** [comment]
I think the biggest skill you need is the ability to pick up a JavaScript library fairly quickly. There is no one library, framework or whatever that you can learn that will help you out more than being flexible. 

In the last two weeks, I've use:

* Angular.js
* ES6 feature to compile to ES5
* Marked.js
* gulp and many gulp-plugins
* Lots of jQuery
* React.js
* Google Maps API
* Google Places API
* Servo.js
* Adobe Edge animation library
* Google's Enabler Library (for Ads) 

Many of these I used for the first time but because I'm pretty good at _JavaScript_, I can pick up these things fairly quickly. 

So - don't try learn everything. Just pick one thing you really like and build lots and lots of stuff. Get good understanding how JavaScript works. 


How do you do this? Just do a lot of work. Build lots of things.

**Comment by ottoo** [comment]
Thanks for the answer. I've been using mainly only Angular at work for about 9 months now, I think it would also be beneficial to fiddle around with things such as ReactJS, NodeJS ect. Once you use a single framework for such a long time you start to wonder about the other stuff out there. You are also right that if you are good with JavaScript, it is easy to pick up any framework because you know how the language works. Maybe I need to dive in to the very specifics of the language too.

Also got your stickers in the mail today :)
