### ISSUE TITLE
Would you ever work for a company?

### ISSUE THREAD

**Issue by darcyclarke** [wesbos/ama#25]
I know you've been able to work with development teams as a freelancer but would you ever consider settling down with a company full-time?

**Comment by wesbos** [comment]
Never say never, but I don't think so. It's just not really my personalility. I've never really had a job, just a few co-ops a few in-house contracts and I never liked any of them. 

For myself, working independently and running my own business has opened many doors. 

* I can work on projects that interest me
* I can teach @HackerYou part time
* I can work on personal projects like <http://commandlinepoweruser.com/> and <http://sublimetextbook.com/>  

Now all of these things are still doable when you have a job, but the biggest reason I don't do that and have  a full time job is so that I can have good balance in my life. I rarely work past 5 and never work on weekends. Taking time off is a piece of cake, and its no big deal to go on an extended vacation where I put in a few hours in the morning before enjoying the day.

Another thing is that I used to be self-employed, which was trading time for money, and that is still a big income earner for me. But now as I launch books + videos + products, I'm more in the seat of a business owner where I can make strategic decisions about marketing and see income come in on days when I'm not working.
