### ISSUE TITLE
Do you have any advice for someone looking to get into video training?

### ISSUE THREAD

**Issue by atuttle** [wesbos/ama#26]
From equipment, to software, to process... If you didn't just figure it out as you went, what did you study? What have you improved on from that? What do you know now that you wish you knew when you first started?

**Comment by wesbos** [comment]
I'm still figuring this all out, but I've learned a ton of the past few years. I didn't study anything, just picked it up as I go. (as I did with programming).

Usually people will say "who cares about equipment!!?!", but I think it's pretty important. We have all turned off tutorials where all you can hear are key clicks, chair squeaks or popping p's - it's distracting when you are trying to focus on a new programming concept. 

I use an [AudioTechnica AT2020](http://wes.io/bvpS) condenser microphone. It's on the same level as something like a blue yeti but it's much smaller and looks better. 

I have it mounted on a cheap-ish [microphone boom arm](http://wes.io/bvKl) and it's mounted inside a [Shock Mount](http://wes.io/bvz0) to stop most of the keyboard vibrations and desk bumps from reaching the microphone

Headphones that don't leak sound are important when doing anything with playback audio, or recording podcasts. For that I use the the new [Bose QC25](http://wes.io/bvtf)

For software, I use [Screenflow 5](http://wes.io/bw29) which is amazing. One of my favourite pieces of software out there. 

My process is pretty simple. I'll first make the thing I want to demo and write a handful of notes on it. On my second monitor I'll have the notes and I'll record on my main one. Since my monitor is huge, I use [xscope](http://xscopeapp.com/) to frame the area I want to record and keep it 16:9.

So - I hit record and get as far as I can. I often screw it up, and will start again. If I do a 5-10 min stint that I'm happy with, I'll stop it, save it to my document, and record the next stint. Once I've got everything done for that video, I'll do some light editing  and export it to YouTube. 

Many devs use scripts where they read what they want, and while that works for some, I feel my videos are better when I'm trying to free-hand explain it to the watchers - it's the same as my in-class teaching style. It comes out less polished, but more real-world. I'll often retain the silly mistakes that the viewers may also hit. Chris Coyier does this and I _love_ it.


So yeah - thats it! I wish I knew more about audio when I started, but I'm also glad it didn't stop me from making videos because those are what propelled my career quite a bit!

**Comment by atuttle** [comment]
How about a photo of all your hardware setup?

**Comment by wesbos** [comment]
![image](https://cloud.githubusercontent.com/assets/176013/8625900/c1901596-26fe-11e5-8d65-6bab47b68dd4.jpg)


I'm not at home right now but this is what my setup looks like when I'm recording. I've got the notes on the right. Recording on the centre and then on another monitor to my left I have audio levels and markers.

**Comment by atuttle** [comment]
Thanks! I see you're using a Magic Mouse. I used one for years but only out of guilt for spending so much on it. Finally switched to a mouse with real ergonomics and I couldn't be happier.

**Comment by wesbos** [comment]
Interesting - I'm a huge keyboard user so I try and not use the mouse too much. 

I had really bad carpel tunnel a few years back and I nursed it back to health with a trackball and split keyboard.

**Comment by vladikoff** [comment]
> We have all turned off tutorials where all you can hear are key clicks, chair squeaks or popping p's - it's distracting when you are trying to focus on a new programming concept.

Hey Wes, what chair do you use? :chair:

**Comment by wesbos** [comment]
I did a ton of research on mine and I ended up with the herman miller aeron. It takes some time to adjust it to be perfect (which is why sometimes people say "I sat in one and it's not that great"), but it's been amazing. 

![](https://scontent-yyz1-1.cdninstagram.com/t51.2885-15/e15/11232661_416048248574899_1064190125_n.jpg?ig_cache_key=OTc4MjE2NjM4NzY5OTA3Njk2.2)

**Comment by vladikoff** [comment]
> I did a ton of research on mine and I ended up with the herman miller aeron. It takes some time to adjust it to be perfect (which is why sometimes people say "I sat in one and it's not that great"), but it's been amazing.

ah Awesome! thanks for the response

**Comment by wesbos** [comment]
:kiss:
