### ISSUE TITLE
What was the first course that actually made money, and how much did you make?

### ISSUE THREAD

**Issue by ryankeeter** [wesbos/ama#273]
You have made several blockbuster courses, but by all accounts, you are just a dude. Now don't get me wrong, you are still an *"expert human"*: you listen, you express empathy, you have wholesome passions, you endeavor for family and legacy, and you enjoy the simple pleasures (i.e. $200 fonts).  Your humanity created a calling that people have responded to, but it must not have always been that way. When was the first time you made money at this "making a course" business model, and how much did you make? Why did you think you could create a career based on that initial success? What did your family think when you said: "hey guys, this might work"?

**Comment by wesbos** [comment]
My first course was SublimeTextBook and it did really well right out the gate. This was because of years of blog/youtube leading up to it and knowing that the Sublime stuff was the first time I hit a nerve with people.

Probably about ~1 year later I knew it could be a career move and I worked towards that, and about 2.5 years after the first launch, I went full time and stopped taking client work.

And yes, I'm just a regular dude :) I think that is why people like my courses :)
