### ISSUE TITLE
Chrome or Firefox Dev Tools?

### ISSUE THREAD

**Issue by MandyMadeThis** [wesbos/ama#36]
I know you were trying out Firefox Dev tools for a month. What was the result of that? Have you converted over to FF now or are you back to your tried and true Chrome?

**Comment by wesbos** [comment]
I did use FireFox dev version for an entire month, I did this so I could give it an honest try rather than poke around at it for a few hours and then spout off prophecies about which is better.

The FireFox dev tools are fantastic. They are fast and there are some really nice features like the event listener icon beside DOM elements, and the CSS transformation visualizer that are amazing. While I really, really liked it, I eventually went back to Chrome. 

While there were minor spots that needed a little polish - most notably the DOM tree would be blank in about 1 in 20 requests, there was deal killer for me: CSS autocompletion.

When I type `wi` and hit `TAB`, it should use the most popular CSS attributes → `width`. Instead it autocompletes to `widows`, which is alphabetically correct, but not very helpful. This is true for a whole bunch of CSS properties where the common ones fall after the alphabetical ones. 

So yeah - they are both amazing, I just prefer Chrome. That doesn't mean they are better, it just means I prefer one over the other and I'd encourage everyone else to give each of them an honest shot and see what works for them!

**Comment by MandyMadeThis** [comment]
Good to know! Speaking of CSS Autocompletion...am I the only one who wishes there was emmet code completion in Dev Tools?! I find myself constantly trying to do things like `m0` + `tab` (`margin:0;`) or `tac` + `tab`  (`text-align: center;`) in dev tools!

**Comment by wesbos** [comment]
I would kill for Emmet in Chrome dev tools!

**Comment by arthurvr** [comment]
@wesbos @MandyMadeThis FYI, https://code.google.com/p/chromium/issues/detail?id=360242.
