### ISSUE TITLE
What do you think of Atom editor?

### ISSUE THREAD

**Issue by sindresorhus** [wesbos/ama#4]

**Comment by wesbos** [comment]
I think it's great!

It's open source, it's JavaScript, it's moving at a fast pace. Amazing 👼

Why don't I switch? I tried for a few weeks and there wasn't really anything better than Sublime Text that it offered me. Switching costs are extremely high, even for tech savvy developers and if there isn't at least a 20-30% improvement, many aren't going to invest the time it takes to switch.

I hate to also pile on the "It's slow" pile everyone is on, but it's slow. They are working on it and I'm keeping eye on it really closely since it's so similar to Sublime.
