### ISSUE TITLE
Have you tried Prezto instead of Oh-My-Zsh, what do you think about it?

### ISSUE THREAD

**Issue by oscarmcm** [wesbos/ama#40]

**Comment by wesbos** [comment]
I haven't tried another shell - I know Fish, plain ZSH, and Prezto are all great alternatives and I'd like to try it out one day, but I've got my environment setup _juuuust right_ currently - it's fast and fits my workflow so I'm pretty happy with it!

**Comment by arthurvr** [comment]
> it's fast and fits my workflow so I'm pretty happy with it!

@wesbos Oh-my-zsh is everything except fast, compared to other solutions :wink:

**Comment by wesbos** [comment]
@arthurvr How do you find it slow? I've never encountered any slowness with it - it might be because I've got really good hardware, but I'd like to know because a few people have asked me about it.

**Comment by arthurvr** [comment]
> How do you find it slow? I've never encountered any slowness with it - it might be because I've got really good hardware, but I'd like to know because a few people have asked me about it.

The base framework is super leaky and is bloated. It reimplements a lot  of things that are already in the shell, has wacky defaults, and since its import into Git it's been not much more than a gigantic plugins directory.

Most people using oh-my-zsh only use it for the fancy prompt anyways and people don't realise that there are a bunch of better(?) alternatives out there. [Pure](https://github.com/sindresorhus/pure) for example, a zsh prompt, does what most people want w/o clutter and way faster. It even fetches Git stuff asynchronously. 

Also, Robby is the only one that sortof maintains oh-my-zsh these days. It has 450 open pull requests...

If you don't experience the slowness, there's at all no problem. Though I'd suggest everybody to just try an alternative for a few days. Big chances that you'll start to experience the slowness when going back afterwards.

Back when I was on oh-my-zsh I started to feel the pain when starting to work on the chromium repo, which is gigantic (bigger than the Linux kernel) and made most of the default prompts simply crash.

FYI, Great read on this topic; https://joshldavis.com/2014/07/26/oh-my-zsh-is-a-disease-antigen-is-the-vaccine/.

**Comment by wesbos** [comment]
Right on - great info! I'm definitely not married to ZSH - I may try another one in the future but the size of repos I work on (medium sized websites) I've never had a single issue.

I teach a ton of beginners who just use the command line basic things like the prompt, file completion and quick navigation (all of what my videos on on) and I find it's really quick  to get them up and running on it, and it makes their command line experience 100x better than a vanilla terminal. There are a ton of either new programmers, or designer-html-css types that meet the terminal for the first time when they use tools like Sass or Gulp and it's important they they don't feel overwhelmed.   

So yeah - maybe I'll do a 2-3 week stint with another terminal in the future, but now if it 'aint broke (for me and most others), then I've got other fish to fry. 

Maybe @robbyrussell can comment on these things?

**Comment by arthurvr** [comment]
>  I'm definitely not married to ZSH - I may try another one in the future but the size of repos I work on (medium sized websites) I've never had a single issue.

To clarify: I love ZSH, was just pointing out that oh-my-zsh isn't as lovely as many people think. 

> I may try another one in the future but the size of repos I work on (medium sized websites) I've never had a single issue. 

Yep. It probably doesn't matter in 99% of the cases anyways and I do fully understand why people use it. I also fully agree with the "don't fix what isn't broken" approach here.

**Comment by wesbos** [comment]
👌 I appreciate the info - now I have a good link to send people to when they ask about it being slow.
