### ISSUE TITLE
What technical skill gave you the most trouble when starting off?

### ISSUE THREAD

**Issue by mcranston18** [wesbos/ama#43]
When I started off, I found learning the intricacies of build tools like Grunt took a while to sink in. What technical skill (whether a build tool, learning a framework, understanding a particularity of a language, etc) gave you the most grief during the learning process?

**Comment by wesbos** [comment]
I've always had a pretty good time understanding concepts, but for me it was the JavaScript syntax. I can remember just thinking I should quit JS and just do HTML/CSS  because it just never worked for me - why would anyone spend time on a language that breaks so easily. I would always mess up the brackets and it just wouldn't run. 

I've come a long way and I'm glad I pushed through that because JS my favourite now.
