### ISSUE TITLE
Starting out as a freelancer

### ISSUE THREAD

**Issue by iferg15** [wesbos/ama#49]
Hi,
I'm looking to do some freelance work as a technical consultant (I'm a draftsman).  I've never done anything on my own before but somehow I have one client ready to go.  The problem is the client is in the US and I have no idea if this complicates things.  The client company has no holdings in Canada.

Were the client a Canadian company, I going to start out very informal.  Quote them an hourly rate, invoice them when the work gets done and keep track of all the records and hire an accountant come tax time (looking into the one you mentioned on your post).  

Have you had international clients, specifically those in the US? Are there speed bumps I should be aware of?

PS - I'm an idiot and have no business registration or number or anything.

Thank you,

**Comment by wesbos** [comment]
I've got lots of US clients, and it's great because the Canadian dollar is so bad right now. Bill in USD!

This is a fairly standard process, first you'll need to setup a business registration. I don't think it's totally necessary, but it will make things easier at the bank. 

Then you simply send them an invoice from your canadian company and they will mail you a cheque.

**Comment by haifzhan** [comment]
@wesbos What kind of company did you register? Federal Corporation or Provincial Corporation? Recently I have a potential customer locates in different cities in Canada. I have to have a registered company if I want to be hired. Any suggestions?  Thanks!
