### ISSUE TITLE
what are your thoughts on rems, ems, % and px? 

### ISSUE THREAD

**Issue by alohavolha** [wesbos/ama#50]
what do you normally prefer to use px/%/em/rem? and why?
I was recently introduced to rem and looks like from now on I will only be using %, rem and occasionally px in my code.

oh, and what do you think about these guys ( i just came across it the other day and though it was interesting, especially the http://txti.es/about )
www.motherfuckingwebsite.com

Thank you!

**Comment by wesbos** [comment]
#### Great question! 

They all do different things, so I use them all when I need their specific functionality. We don't have all these different ways because one replaces an outdated way, they all have their own pros/cons. 

`em`s are great when you want children to scale up and down according to the parent. Just change the parent, and the children will all be a multiple of that. 

I use `rem`s quite a bit for working with font sizes because I really like how you can set a base on your `html` tag and then use everything as a multiple based off of that.

When I teach, I start off with pixels because it's the easiest to understand and then we move into using rems for type and `%` for layout.

Sizing elements is almost always done in `percentages`, often using `calc(100% - 2rem)` to create a gutters / allow for margins. 

For media queries, I mostly use pixels. I talked a lot [more about it here](https://github.com/wesbos/ama/issues/35).

**Comment by wesbos** [comment]
Oh, and I think sites like motherfuckingwebsite.com make a good point about speed, size and simplicity but totally throw any banding/selling objectives/UX out the window. Problems that websites solve aren't that cut and dry.
