### ISSUE TITLE
In hindsight, what advice do you wish someone had given you at age 20?

### ISSUE THREAD

**Issue by Widdershin** [wesbos/ama#53]

**Comment by wesbos** [comment]
Ooohhh goood one. 

For some context, I'm 27 now, and at age 20 I was starting to get some momentum as a web developer - I was learning WordPress and starting to understand CSS.

I'd say this advice goes for anyone just getting into web development:

1. **Programming gets easier**. I don't mean that it's a walk in the park - I'm still challenged every day, but I have way less "I absolutely cannot do this and I don't understand it at all" moments. I don't have those "I want to quit this because its not for me" feelings. You know what I mean? Learning to code at first was really hard for me, and I'm glad I pushed through that.

2. Life is a series small course corrections - one thing almost always leads to another. I used to try and plan what my career would look like, give myself a 5 year plan but slowly I'm realizing that new opportunities come along every 6 months and slowly morph your life and your career. So, I guess my advice would be to just have an open mind as to what you life will look like. 

3. Save your money and make your money. This is one thing I actually followed - I didn't spend a ton when I was in university. That combined with doing freelance work means I had no debt when I graduated and it allowed me to do whatever the hell I wanted to do™. For me, this meant taking a risk on freelancing, which panned out to running my own company now!
