### ISSUE TITLE
What do you make your living from?

### ISSUE THREAD

**Issue by anselmh** [wesbos/ama#55]
Hey,

I’m curious where you generate your income from. Can you live from your video series and writings or if not, is it usual client work which pays your bills (if so, what share do you generate from your community-work/writing/videos)?
Would love to see more open data on how and if people can live from open source work.

Thanks,
Anselm

**Comment by wesbos** [comment]
Great question!  I always love hearing about how others make their living, so I'm happy to share mine. 

A good chunk of my income at the moment comes from consulting - probably 50 - 60% if I were to guess. I work with startups/companies doing front end dev / CSS3  / JavaScript / Node / WordPress. 

I work with [HackerYou](http://hackeryou.com) where I teach HTML/CSS/JavaScript/WordPress/you-name-it

My book has done extremely well in the year that it has been up. It's my only paid product at the moment but accounts for a good chunk of my income. The last few months have been spent creating [Command Line Power User](http://commandlinepoweruser.com) and [Flexbox.io](http://flexbox.io) - they are free, but really help with both my reputation as well as indirectly making sales of my other book.  I'm working on two more paid products right now which I'm super excited about. 
 
My writings on my blog and my youtube videos don't make too much - between a few affiliate links and youtube ads I see about $200 / month.  That said, because I help people understand how to use open source software, they often lead to well paying consulting jobs.  All of my best work has come from people finding my blog posts or youtube videos and them hiring me to implementing something similar for them.

**Comment by anselmh** [comment]
Thank you, this is great to read and hopefully inspiring to others :)

**Comment by knksmith57** [comment]
would be super interested to hear (if you're still open to it!) how this has changed with the _crazy success_ of your online course offerings

**Comment by wesbos** [comment]
Yeah! Want to ask another question on this ama so I can write a new one?
