### ISSUE TITLE
Blogging as a newbie dev

### ISSUE THREAD

**Issue by gethinoakes** [wesbos/ama#57]
You've said in other answers that blogging is a good way to grow your career and learn and so this may come across as a bit of a daft question.

Would you recommend someone blog about things they learn when compared to everything they could learn it is really simple stuff.

I recently got a job out of university as a front end developer, and I've been thrown into javascript, angular, typescript, gulp etc. and just feel like everything that's come into my head has gone straight back out so I was contemplating writing posts on a blog about what I'm learning, or some code that did something or when I figured something out.

I feel a little embarrassed as the stuff seems so simple in the first place and maybe the web community if they stumbled upon my posts would rip me apart, unless they're all like you as you seem like a genuinely nice guy...

**Comment by wesbos** [comment]
This is such a good question - I need a bit to answer it because I've got a lot to say about it. So sit tight!

**Comment by wesbos** [comment]
Thanks for the question - it's a great one because I felt like this and can still feel like this today. 

I would definitely blog about what you are currently learning. There are a few reasons behind it. First, when you need to explain something to someone else, you gain massive clarity. When I create notes and teach my students, I really get to know how these things works. 

Second, it's a fantastic reference for yourself when you forget how to do things. I can't tell you how many times I've googled for an answer and found either my own blog post or my own stack overflow answer. 

When you blog about a topic, you also establish yourself as an expert in that area. Whether you are or not, you will seem like it and slowly you will become one. Most of my blog posts are written because I'm exploring some new technology and I want to help others figure it out as well. 

As for things being too simple - no way, no way. I always google for simple stuff and I love when there are short tutorials I can check out.  I can't tell you how many of my tiny little posts have blown up and give me lots of traffic. 

Same goes for if there is already something online. There will _always_ be another blog post about the topic that you are writing about. That doesn't mean you can't write a better one, or in my case, I explain things in a certain way that clicks with a certain type of developer. It's not for everyone, but quite a few people tell me they like my style of teaching much better than other resources. 

So, yes. Do it! You will be helping yourself out massively as well as thousands of developers  to come in the future.

**Comment by bhaveshgohel** [comment]
Sorry for reopening, just wanted to say Thanks for the answer @wesbos :smiley:

**Comment by gethinoakes** [comment]
Thanks for the answer & encouragement :+1: I actually just started thinking of a design for my blog last night and will hopefully get it up in a week or two so that I can start :) 

Thanks again!

**Comment by wesbos** [comment]
Amazing - let me know when it's up!

**Comment by gethinoakes** [comment]
Ok, so it took me longer than I had hoped and I'm still working out kinks in my current theme - it's not the theme/design I had in mind but I've just done this simple one for now so I could start blogging (without having to use a default theme). I've backdated the first post to a week ago as I made notes on the JS book I'm reading in the past week so will be backdating those too.

http://gethinoakes.com

Thanks again :)

**Comment by wesbos** [comment]
@gethinoakes Right on - great job! Now keep on blogging :)
