### ISSUE TITLE
What are the best non-technical books you've read?

### ISSUE THREAD

**Issue by robbbz** [wesbos/ama#63]

**Comment by wesbos** [comment]
I don't really read and when I do it's audio books. 

I've done a ton of business books, and the one that sticks out in my mind almost a year later is Pitch Perfect - an unfortunate name because it has nothing to do with the singing movie, nor "pitching startups".

It's all about how to effectively communicate with people. Getting ideas across and understand how to phrase things is so important and this book really helped me. 

http://www.harpercollins.com/9780062273222/pitch-perfect
