### ISSUE TITLE
How have you garnered such a strong personal brand?

### ISSUE THREAD

**Issue by tylermcginnis** [wesbos/ama#67]
I find the personal brand side of what you do extremely interesting because you've done such an amazing job at it. My go to has been to try to "create content people want to share" and the rest kind of takes care of itself. Can your personal brand be accredited to blogging, speaking, writing, hustling or is there something you did that I'm missing. You rock man.

**Comment by wesbos** [comment]
Great question! I took so long to answer this because I'm really having a hard time pinning it down. Maybe some others can chime in on what they think it might be? 

Creating good content is by far the biggest part of it. When you create good content, it makes the rest of it really easy. It's probably about 90-95% of it. 

That said, there is so much good content out there that never gets the eyeballs that it should just because many devs don't have that last 5% which is making things visible.  

So, what is it accredited to? I realize how important having a person brand is to my job - it helps me get work and sell products. So just like I spend time every week learning new things and doing my client work, I spend time working on my "personal brand" (as cheezy as that sounds).

What is that?

* Applying to conferences - writing talks
* Writing blog posts
* Writing tweet tips (I've been on twitter for 9 years so I have an unfair advantage) 
* Interacting with people on twitter
* Creating free video series
* Helping people in chat rooms and on stack overflow
* Speaking at meetups

This obviously takes tons of time, but I'm just now starting to see it pay me back for my time. 

The other side of it is that I like to show a bit of myself in everything I do. Most people know that I have a daughter, that I use a specific blue theme, that I have a cool office and what my dog looks like. 

By letting people in on these parts of my life and by keeping nice open paths of communication (My tweet DMs are open, phone number is online, email is available) I think I seem fairly approachable and relatable to other devs. 

So yeah - I think you can boil it down to 1) Create good content 2) the daily hustle of being visible and 3) trying to be a nice, approachable person.

**Comment by kentcdodds** [comment]
I've just started my career and developing my brand. I've done many of these same things and it's been huge for me. I can definitely second the value of a personal brand and these specific suggestions for developing it.

**Comment by kentcdodds** [comment]
Oh, and the beauty of things is that there's totally enough room for everyone to do this stuff. Life is only better when more of us do this stuff for the community.

**Comment by lamosty** [comment]
Thanks for the advice, you are very cool!

**Comment by zcserei** [comment]
@tylermcginnis it's so interesting seeing this question from you from over a year ago - last year (I mean 2016, wow) I already learnt a lot from you, too.

Good job, everyone! Thanks for the value you are sharing!

**Comment by tylermcginnis** [comment]
@zcserei Thank you and you are very welcome! Here's to a great 2017 for all of us 🎉
