### ISSUE TITLE
Subject trend year

### ISSUE THREAD

**Issue by juanespina** [wesbos/ama#70]
What do you think will be most talked about and studied this year,  example API, Spec and tools.

**Comment by juanespina** [comment]
cc @wesbos

**Comment by wesbos** [comment]
I think with the rising popularity of React and the release of Angular2, we will see (and already are seeing) a huge shift in developers moving over to ES6/7 and build tools for their JavaScript. 

Things like Browserify, Webpack and babel are the first to pick up, but I think because everyone is moving over to this, we will see tools that are easier to use developed. Something like a react-cli.

**Comment by wesbos** [comment]
Thanks for the question!

**Comment by juanespina** [comment]
thanks for the answer
