### ISSUE TITLE
Did you develop your own course hosting platform?

### ISSUE THREAD

**Issue by nickjj** [wesbos/ama#71]
Judging by some of your blog posts and your lack of presence on flea market style course hosting platforms like Udemy it's a safe bet that you either created your own course hosting platform, or you've licensed one from a third party.

I haven't signed up for any of your courses, so I'm not sure what the platform looks like beyond a course's landing page but I'd be curious to hear what challenges you've faced creating your own platform, and how you manage to promote your own courses.

For instance, your React for Beginners course was announced on Twitter on Nov 3rd 2015 and the website at the time of opening this issue is reporting 3,500 sales. That's an impressive amount of sales for about 2 months, especially since you likely get to keep 95%+ of the revenue.

**Comment by wesbos** [comment]
> Judging by some of your blog posts and your lack of presence on flea market style course hosting platforms like Udemy it's a safe bet that you either created your own course hosting platform, or you've licensed one from a third party.

Yep - it's a custom Node + Express + Mongodb stack. I run two of them - one for ReactForBeginners.com and one for SublimeTextBook.com. They both run on a single Digital Ocean instance on their own port, and then I use Nginx to hook up the SSL certs and the custom domains. 

> I haven't signed up for any of your courses, so I'm not sure what the platform looks like beyond a course's landing page but I'd be curious to hear what challenges you've faced creating your own platform, 

I chose to run my own platform so that I could have total control over the buying experience, the learning experience and the audience after the fact. I'm sure Udemy is great because they have their own built in audience, but I'm not about to put all my eggs in someone else's basket. 

It's hard to run your own - things can go down and features take time to develop. I'm currently re-thinking what a single platform would look like. Get rid of the multiple node instances and build it into a platform that can handle everything.

>and how you manage to promote your own courses.

It's mostly word of mouth. I've used twitter and email to get the initial word out, but I hate to bug people on my list so I don't send to that too often. Once the initial word is out, others recommend it and word starts to spread. 

> For instance, your React for Beginners course was announced on Twitter on Nov 3rd 2015 and the website at the time of opening this issue is reporting 3,500 sales. That's an impressive amount of sales for about 2 months, especially since you likely get to keep 95%+ of the revenue.

95% would be high. It seems like an all-profit business from here, but lots of the profits go to affiliates (I pay 40%) who help share the word, testing different advertising methods, stickers (surprisingly expensive), server costs, bandwidth, etc...

**Comment by nickjj** [comment]
Thanks.

Yeah 95% is high. I figured 3% for your payment processor and minimal amounts on hosting. Yep stickers are no joke haha, I offer them too for my courses. I get them from Stickermule.

I didn't realize you were using affiliates. Would you mind sharing which affiliate networks you use?

**Comment by wesbos** [comment]
It's all built into my system - each affiliate has their own link that drops a 2 week cookie. When someone buys a product, I tag that purchase with the referral cookie. Then once a month I'll run some reports and send out the $$ to my affiliates.

**Comment by nickjj** [comment]
But which affiliate networks are you using specifically?

I thought it was something like:

- You create a unique URL (maybe with a coupon code)
- You give it to an affiliate
- They promote it to their crowd
- You give them 40%

**Comment by wesbos** [comment]
I'm not sure what you mean by networks?

**Comment by nickjj** [comment]
Sites like https://www.clickbooth.com/ and others where they will promote your product and take a ~40% cut. Not sure if clickbooth takes 40% exactly, but that's the general pattern.

**Comment by wesbos** [comment]
Ohh no I only give access to users who I trust and have an audience that lines up with my own - it's not an open things where anyone can spam the link around. I only have about 5 affiliates.

**Comment by nickjj** [comment]
Ah, ok thanks.
