### ISSUE TITLE
Do you feel like a backend dev can *learn* to be a decent designer.

### ISSUE THREAD

**Issue by jwalton512** [wesbos/ama#82]
Is designing (web, graphic, etc) something you have a natural knack for, or is it something you can learn to be decent (or even good) at.

**Comment by wesbos** [comment]
It's 100% something that can be learned - it comes easier to some than others, but I don't think it's something you are born with or coincides with a certain personality type. 

Good designers are good because they put in the time and created thousands of things. I learned good design by taking people's PSDs and implementing them in CSS. When I would try and match the CSS with the PSD I would realize how much a difference things like padding, margins, font sizes, layout, colours and all that really did matter. 

I owe a lot of my design chops to cranky designers who made me go back and change line height or add 10 extra pixels of padding. It doesn't seem like a big deal, but once I implemented the changes, the site just felt better to use. 

So, if you want to get good, take a few good designs from Dribble and try to replicate it 100%. The attention to detail will really show what it takes.

**Comment by jwalton512** [comment]
Awesome information!  Thanks for the response!

**Comment by olegon** [comment]
> So, if you want to get good, take a few good designs from Dribble and try to replicate it 100%. The attention to detail will really show what it takes.

hoho, learn by doing! :construction_worker:

**Comment by saltcod** [comment]
I'd also be surprised if asking a good designer for some real quick feedback wouldn't be helpful.  Having a second pair of eyes point out some smaller issues (colours, font sizes, paddings, margins, etc), over and over and over again on different projects are bound to eventually make you a better designer.

**Comment by jwalton512** [comment]
@saltcod thanks!
