### ISSUE TITLE
What are your daily habits?

### ISSUE THREAD

**Issue by AntonNiklasson** [wesbos/ama#96]

**Comment by wesbos** [comment]
Ohh good question - anyone care to be more specific? I don't really do anything out of the ordinary but I can shed light on specific things like email, projects, focus, whatever

**Comment by mattwillmott** [comment]
I'd specifically like to know what methods you use to keep focused, and how you schedule email in your workday so that it doesn't get in the way of everything else.

**Comment by AntonNiklasson** [comment]
Are you always working say 8 hours straight? Or do you split it up in some way?

Do you wake up and start coding? What does the first 90 minutes of an ideal day look like for you?

**Comment by AntonNiklasson** [comment]
Are you more productive during some parts of the day? Why is that?

**Comment by wesbos** [comment]
Thanks for the question!

I can't say that I've got this all figured out, but I do have some thoughts about where I currently am, so here are a few things I'll rattle off:

### Email

I do email 1 or 2 times per day  and just batch process it. I have my email open all day just incase something important or easy comes in, but I'm not a slave to my email and it's been amazingly freeing.  Now, I try and make the decision and have the email done with whenever I open it. 

I figured out about a year ago that I didn't have an email problem, but a decision problem, I'd open an email up and defer it to later because I didn't feel like making a decision on whatever was in the email. 

I get a ton of email. I had zero emails on Friday afternoon. Now it's Monday morning and I have about 50 things to deal with. I'll deal with most of that in about 25 minutes because I have a huge set of snippets that automates most of the stuff that comes in. 

I'd say I respond to about 95% of my email, but 5% gets lost. I don't really fret that too much. 

### productivity?

I don't wake up and start coding - I've got kids and a wife that need to be fed so I spend the first 2-3 hours hanging out with my family, having breakfast and playing. 

I start work around 9am every day — the first thing I do is open up Things.app and dump everything I need to do for the day. If I have calls to make, they happen right away. If I must take calls / do skype, I've been trying to enforce a strict "only calls at 9am". My Google calendar defaults to 15 minutes because most things can get done in 15 mins. 

Once I have my 2-3 things that I will work on for the day, I'll just start working on them. I'll usually get distracted by twitter a few times through the day, which is when I'll take a break and work on a 🔥 hot tip. 

Other than that I don't think it's anything amazing. I just try and keep my days clear so I have long stretches to work on things. 

### Other things?

Aggressively prune all the busy work from your working life and focus on the big picture. Especially with a business, It's easy to get caught up in the busy work and not work on the stuff that actually drives your business forward. It's the difference between working in your business (paying bills, evaluating different website servers) and on your business (building the next series, focusing on strategy). 

I hope that helps. Feel free to open another one if you have more specific questions: )
